### ISSUE TITLE
facility changes and page refresh

### ISSUE THREAD

**Issue by ychoy** [edupc/webportal#40]
In order to see changes (edit/delete/create), the user needs to refresh. Fix the issue so the user doesn't have to refresh the page to see the changes made

**Comment by anibalsolon** [comment]
I've done some work about this functionality.

Apollo creates a global store in order to cache the results from queries and mutations. But we are not properly using it, because we are not referencing to a valid ID field: 
https://github.com/descartae/webportal/commit/07cfd1de0b9f379321cdb9b0ef50b51cd807847f#diff-14b1e33d5bf5649597cdc0e4f684daddL50

By only correcting this, we got the list update when editing a facility.

Inserting and deleting works differently. When a mutation is called, we must provide an option called `refetchQueries`, in order to re-execute the list query. It is also working now.

In every case, it was required to introduce Fragments. Our fragments basically define which fields should be retrieved when executing queries/mutations about facilities. By using it, we guarantee that no field is forgotten and the store update works seamlessly.
